# Generated by Django 4.2 on 2023-04-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.AlterModelOptions(name="item", options={},),
    ]
